manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-pete
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmk-pete
      revision: zephyr-2.5-upgrade
      import: app/west.yml
  self:
    path: config
